# Rscript -e "bookdown::render_book('.', 'all')"

version: '3'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: pcourbin/bookdown:base
    container_name: bookdown_base
    environment:
      mainFile: index.Rmd
    volumes:
      - ./book:/book
  extended:
    build:
      context: .
      dockerfile: Dockerfile.extended
    image: pcourbin/bookdown:extended
    container_name: bookdown_extended
    environment:
      mainFile: index.Rmd
    volumes:
      - ./book:/book
  user:
    build:
      context: .
      dockerfile: Dockerfile.user
      args:
        bookdownuser: docker
        uid: 1000
    image: pcourbin/bookdown:user1000
    container_name: bookdown_user
    environment:
      mainFile: index.Rmd
    volumes:
      - ./book:/book
